# Generated by Django 4.2.1 on 2024-02-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(default='https://laprimera.pe/wp-content/uploads/2023/09/000993584W.jpg', upload_to='proyecto_img/')),
                ('lenguaje', models.CharField(max_length=120)),
            ],
        ),
    ]
